force-app/main/default/objects/FullSetList__c/FullSetList__c.object-meta.xml
<CustomObject>
    <label>FullSetList</label>
    <nameField>
        <label>FullSetList Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FullSetLists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FullSetList__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>FullSetLists</relationshipLabel>
    <relationshipName>FullSetLists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FullSetListTemplate__c/FullSetListTemplate__c.object-meta.xml
<CustomObject>
    <label>FullSetListTemplate</label>
    <nameField>
        <label>FullSetListTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FullSetListTemplates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateFullSetList.cls
public with sharing class CreateFullSetList implements Queueable{
    private List<Opportunity> oppList;
    public CreateFullSetList(List<Opportunity> oppList){
        this.oppList = oppList;
    }
    public void execute(QueueableContext context){
        List<FullSetList__c> fsList = new List<FullSetList__c>();
        List<FullSetListTemplate__c> flList = [SELECT Description__c, DueDate__c, Order__c FROM FullSetListTemplate__c];
        for(Opportunity opp : oppList){
            for(FullSetListTemplate__c fslt : flList){
                fsList.add(new FullSetList__c(
                    Description__c = fslt.Description__c,
                    DueDate__c = Date.today(),
                    Order__c = fslt.Order__c,
                    Opportunity__c = opp.Id)
                );
            }
        }
        insert fsList;
    }
}