force-app/main/default/objects/Core_Account__c/Core_Account__c.object-meta.xml
<CustomObject>
    <label>Core Account</label>
    <nameField>
        <label>Core Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Core Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Core_Account__c/fields/Sign_up_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Sign_up_Company_Name__c</fullName>
    <label>Sign up Company Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Core_Account__c/fields/Sign_up_Company_Website__c.field-meta.xml
<CustomField>
    <fullName>Sign_up_Company_Website__c</fullName>
    <label>Sign up Company Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Core_Account__c/fields/Sign_Up_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Sign_Up_First_Name__c</fullName>
    <label>Sign Up First Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Core_Account__c/fields/Sign_Up_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Sign_Up_Last_Name__c</fullName>
    <label>Sign Up Last Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Core_Account__c/fields/Sign_Up_Personal_Email__c.field-meta.xml
<CustomField>
    <fullName>Sign_Up_Personal_Email__c</fullName>
    <label>Sign Up Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/CoreAccountTriggerHandlerTest.cls
@isTest
public with sharing class CoreAccountTriggerHandlerTest {
    @isTest static void createCoreAccountWithAllFields(){
        List<Core_Account__c> coreAccList = new List<Core_Account__c>();
        for (Integer i = 0; i < 5; i++) {
            coreAccList.add(new Core_Account__c(Sign_Up_Company_Name__c = 'testName ' + i,
            Sign_Up_Company_Website__c = 'test' + i + '.com',
            Sign_Up_First_Name__c = 'first Name ' + i,
            Sign_Up_Last_Name__c = 'last Name ' + i,
            Sign_Up_Personal_Email__c = 'email' + i + '@mail.com'));
        }
        Test.startTest();
        insert coreAccList;
        Test.stopTest();
        System.assertEquals(5, [SELECT Id FROM Account].size(), 'should be 5');
        System.assertEquals(5, [SELECT Id FROM Contact].size(), 'should be 5');
    }
    @isTest static void createCoreAccountWithLastNameOnly(){
        List<Core_Account__c> coreAccList = new List<Core_Account__c>();
        for (Integer i = 1; i < 5; i++) {
            coreAccList.add(new Core_Account__c(Sign_Up_Company_Name__c = 'testName ' + i,
                                                Sign_Up_Last_Name__c = 'last Name ' + i)
            );
        }
        Test.startTest();
        insert coreAccList;
        Test.stopTest();
        System.assertEquals(0, [SELECT Id FROM Account].size(), 'should be 0');
        System.assertEquals(0, [SELECT Id FROM Contact].size(), 'should be 0');
        System.assertEquals(CoreAccountTriggerHandler.LEAD_STATUS, [SELECT Status FROM Lead LIMIT 1].Status, 'should be ' + CoreAccountTriggerHandler.LEAD_STATUS);
    }
}